name: secret_santa_client
description: An absolute bare-bones web app.
version: 1.0.0
repository: https://github.com/mchach24/secret-santa

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.0
  build_test: ^2.1.6
  build_web_compilers: ^3.2.0
  lints: ^2.0.0
